language: python
# with next we get on container based infrastructure, this enables caching
sudo: false
python:
  - 3.7.2
cache:
  pip: true

before_install:
  - virtualenv .
  - bin/pip install zc.buildout

install:
  - bin/buildout

script:
  - bin/test
